name: consolidator-env
channels:
 - conda-forge
 - defaults
dependencies:
 - python==3.12
 - numpy
 - ome-zarr>=v0.16.0
 - zarr>=v3.2.0
 - tifffile
 - imagecodecs
 - imageio
 - psutil
 - pip
 - pip:
   - ome-types>=0.6.2
   - rocrate>=0.15.0
